name: source_gen_test
publish_to: none
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.33.3 <0.36.0'
  build: '>=0.12.6 <2.0.0'
  build_test: ^0.10.0
  path: ^1.3.2
  source_gen: ^0.9.0
  test: ^1.3.3
